In [1]:
import numpy as np

In [2]:
a = np.ones((2, 1), dtype=float)
print(a)
print(a.shape)

[[1.]
 [1.]]
(2, 1)


In [3]:
from network import NeuralNetwork
from dense import DenseLayer

In [4]:
x = np.random.random((3))
y = np.random.random((3))

print(f"x: {x}'\ny: {y}\nx * y: {np.dot(x, y).reshape(-1, 1)}\nx * y + 1: {np.dot(x, y).reshape(-1, 1) + 1}")

x: [0.22898803 0.18015321 0.53402436]'
y: [0.57168756 0.50010667 0.98899341]
x * y: [[0.749152]]
x * y + 1: [[1.749152]]


In [5]:
def y(x):
    return np.dot([1, 2], x) + 1

In [6]:
def test_samples(size):
    x_set = []
    y_set = []
    for _ in range(size):
        x = np.random.random(2)
        x_set.append(x.reshape(-1, 1))
        y_set.append(y(x).reshape(-1, 1))
    return x_set, y_set

In [7]:
x = np.random.random((5, 1))
print(x)
s = 0
for i in range(x.shape[0]):
    s += x[i, 0] ** 2
print((x * x).sum(), s)


[[0.33994589]
 [0.1978052 ]
 [0.04112785]
 [0.99408416]
 [0.9183257 ]]
1.9879070003699986 1.9879070003699986


In [8]:
network = NeuralNetwork([
    DenseLayer(2, 3),
    DenseLayer(3, 1)
], 0.01)

epochs = 1000
size = 9
x_set, y_set = test_samples(size)
for epoch in range(epochs):
    print(f"Epoch: {epoch}")
    network.train(x_set, y_set)


Epoch: 0
[array([[0.85801204],
       [0.58271256]]), array([[1.26060922],
       [0.39066333],
       [1.16325955]]), array([[1.76340395]])]
MSE: 1.587683679101897;                    Learning rate: 0.01
[array([[0.48648533],
       [0.64949762]]), array([[1.01313487],
       [0.2906442 ],
       [1.00291912]]), array([[1.68261033]])]
MSE: 1.2163227749056758;                    Learning rate: 0.01
[array([[0.01729412],
       [0.85795597]]), array([[0.77641855],
       [0.15564954],
       [0.90024215]]), array([[1.56443781]])]
MSE: 1.366019219038233;                    Learning rate: 0.01
[array([[0.24704404],
       [0.2553526 ]]), array([[0.55243932],
       [0.22958996],
       [0.53246558]]), array([[1.4387456]])]
MSE: 0.10176331948537054;                    Learning rate: 0.01
[array([[0.7888377 ],
       [0.84734313]]), array([[1.51475131],
       [0.48975949],
       [1.45836096]]), array([[2.2758978]])]
MSE: 1.4583609425029764;                    Learning rate: 0.01
[array([[

In [9]:
for layer in network.layers_:
    print(layer.w_)

[[0.67110889 1.2063895 ]
 [0.26449826 0.31348431]
 [0.48777464 1.24606717]]
[[0.82320182 0.37656217 0.71332541]]


In [10]:
x_test_set, y_test_set = test_samples(10)
for i in range(10):
    print(f"Predicted: {network.predict(x_test_set[i])}, Expected: {y_test_set[i]}")

Predicted: [[2.03621045]], Expected: [[2.03621036]]
Predicted: [[2.73688966]], Expected: [[2.73688973]]
Predicted: [[2.84457911]], Expected: [[2.84457902]]
Predicted: [[3.24873826]], Expected: [[3.24873822]]
Predicted: [[3.02411149]], Expected: [[3.0241116]]
Predicted: [[3.12958242]], Expected: [[3.12958252]]
Predicted: [[2.81337682]], Expected: [[2.81337693]]
Predicted: [[2.95575964]], Expected: [[2.95575966]]
Predicted: [[2.89219929]], Expected: [[2.89219943]]
Predicted: [[2.3037942]], Expected: [[2.30379416]]
